import Header from './header'
import MyComponent from './test'
import HeaderTrigger from './HeaderTrigger'
import Hero from './hero'
import Button from './button'
import LocationCard from './contact-us/locationCard'
import MessageUsForm from './contact-us/messageUsForm'
import MessageUs from './contact-us/messageUs'
import EventCard from './trainings-&-seminars/eventCard'
import EventsList from './trainings-&-seminars/eventsList'
import Sorter from './trainings-&-seminars/sorter'
import { CategoryBanner } from './products/categoryBanner'
import { BrandSlider } from './embla/brandSlider'
import FeaturedProductsList from './products/featuredProductsList'
import ProductCard from './products/productCard'
import CatalogueCard from './resources-pages/catalogueCard'
import AboutF from './homepage/aboutF'
import Strengths from './homepage/strengths'
import Reach from './homepage/reach'
import { BrandSliderF } from './embla/brandSliderF'
import BrandsF from './homepage/brandsF'
import TestimonialsF from './homepage/testimonialsF'
import EventsF from './homepage/eventsF'
import ProstigeF from './homepage/prostigeF'
import ViberBanner from './contact-us/viberBanner'
import QuotationGUide from './resources-pages/quotationGuide'
import OrderingGuide from './resources-pages/orderingGuide'
import SideMenu from './sideMenu'
import Faq from './resources-pages/faq'
import TestimonialCard from './testimonials/testimonialCard'
import SalesAgentSearchBar from './resources-pages/agentSearchBar'
import SalesAgentCard from './resources-pages/salesAgentCard'
import BrandLogo from './brands/brandLogo'
import BrandInfo from './brands/brandInfo'
import SearchBar from './searchBar'
import BrandCategoriesList from './brands/brandCategoriesList'
import ProdInfo from './products/prodInfo'
import HeroBanner from './homepage/heroBanner'
import HomeLoading from './homepage/homeLoading'
import OurStory from './homepage/ourStory'
import OrderF from './homepage/orderF'
import PHero from './prostige/pHero'
import PBanner2 from './prostige/pBanner2'
import PBanner3 from './prostige/pBanner3'
import PBanner4 from './prostige/pBanner4'
import PBanner5 from './prostige/pBanner5'
import PBanner6 from './prostige/pBanner6'
import PBanner7 from './prostige/pBanner7'
import PBanner8 from './prostige/pBanner8'
import PBanner9 from './prostige/pBanner9'
import Breadcrumbs from './products/breadcrumbs'
import ProdContent from './products/prodContent'
import QuoteForm from './products/quoteForm'
import AboutHero from './about/hero'
import AboutS01 from './about/auSection01'
import AboutS02 from './about/auSection02'
import AboutS03 from './about/auSection03'
import AboutS04 from './about/auSection04'
import AboutS05 from './about/auSection05'
import AboutS06 from './about/auSection06'
import AboutS07 from './about/auSection07'
import AboutS08 from './about/auSection08'
import AboutS09 from './about/auSection09'
import AboutS10 from './about/auSection10'


export {
    Header, MyComponent, HeaderTrigger, Hero, Button, LocationCard, MessageUsForm, EventCard, EventsList, Sorter, CategoryBanner, BrandSlider, FeaturedProductsList, ProductCard, CatalogueCard, AboutF, Strengths, Reach, BrandSliderF, BrandsF, TestimonialsF, EventsF, ProstigeF, ViberBanner, QuotationGUide, OrderingGuide, SideMenu, Faq, TestimonialCard, SalesAgentSearchBar, SalesAgentCard, BrandLogo, BrandInfo, SearchBar, BrandCategoriesList, ProdInfo, HeroBanner, HomeLoading, OurStory, OrderF, PHero, PBanner2, PBanner3, PBanner4, PBanner5, PBanner6, PBanner7, PBanner8, PBanner9, Breadcrumbs, ProdContent, QuoteForm, MessageUs, AboutHero, AboutS01, AboutS02, AboutS03, AboutS04, AboutS05, AboutS06, AboutS07, AboutS08, AboutS09, AboutS10
}