import Header from './header'
import MyComponent from './test'
import HeaderTrigger from './HeaderTrigger'
import Hero from './hero'
import Button from './button'
import LocationCard from './contact-us/locationCard'
import MessageUsForm from './contact-us/messageUsForm'
import EventCard from './trainings-&-seminars/eventCard'
import EventsList from './trainings-&-seminars/eventsList'
import Sorter from './trainings-&-seminars/sorter'
import { CategoryBanner } from './products/categoryBanner'
import { BrandSlider } from './embla/brandSlider'
import FeaturedProductsList from './products/featuredProductsList'
import ProductCard from './products/productCard'
import CatalogueCard from './resources-pages/catalogueCard'
import { AboutF } from './homepage/aboutF'
import { Strengths } from './homepage/strengths'
import { Reach } from './homepage/reach'
import { BrandSliderF } from './embla/brandSliderF'
import { BrandsF } from './homepage/brandsF'
import { TestimonialsF } from './homepage/testimonialsF'
import { EventsF } from './homepage/eventsF'
import ProstigeF from './homepage/prostigeF'
import ViberBanner from './contact-us/viberBanner'
import QuotationGUide from './resources-pages/quotationGuide'
import OrderingGuide from './resources-pages/orderingGuide'
import SideMenu from './sideMenu'
import Faq from './resources-pages/faq'
import TestimonialCard from './testimonials/testimonialCard'
import SalesAgentSearchBar from './resources-pages/agentSearchBar'
import SalesAgentCard from './resources-pages/salesAgentCard'
import BrandLogo from './brands/brandLogo'
import BrandInfo from './brands/brandInfo'
import SearchBar from './searchBar'
import BrandCategoriesList from './brands/brandCategoriesList'
import ProdInfo from './products/prodInfo'

export {
    Header, MyComponent, HeaderTrigger, Hero, Button, LocationCard, MessageUsForm, EventCard, EventsList, Sorter, CategoryBanner, BrandSlider, FeaturedProductsList, ProductCard, CatalogueCard, AboutF, Strengths, Reach, BrandSliderF, BrandsF, TestimonialsF, EventsF, ProstigeF, ViberBanner, QuotationGUide, OrderingGuide, SideMenu,Faq, TestimonialCard, SalesAgentSearchBar, SalesAgentCard, BrandLogo, BrandInfo, SearchBar, BrandCategoriesList, ProdInfo
}