import Header from './header'
import MyComponent from './test'
import HeaderTrigger from './HeaderTrigger'
import Hero from './hero'
import Button from './button'
import LocationCard from './contact-us/locationCard'
import MessageUsForm from './contact-us/messageUsForm'
import EventCard from './trainings-&-seminars/eventCard'
import EventsList from './trainings-&-seminars/eventsList'
import Sorter from './trainings-&-seminars/sorter'
import { CategoryBanner } from './products/categoryBanner'
import { BrandSlider } from './embla/brandSlider'
import FeaturedProductsList from './products/featuredProductsList'
import ProductCard from './products/productCard'
import CatalogueCard from './resources-pages/catalogueCard'
import { AboutF } from './homepage/aboutF'
import { Strengths } from './homepage/strengths'
import { Reach } from './homepage/reach'
import { BrandSliderF } from './embla/brandSliderF'
import { BrandsF } from './homepage/brandsF'
import { TestimonialsF } from './homepage/testimonialsF'
import { EventsF } from './homepage/eventsF'
import ProstigeF from './homepage/prostigeF'
import SitemapF from './sitemap/sitemapF'
import CareersF from './careers/CareersF'
import NewsUpdatesF from './news-updates/NewsUpdatesF'

export {
    Header, MyComponent, HeaderTrigger, Hero, Button, LocationCard, MessageUsForm, EventCard, EventsList, Sorter, CategoryBanner, BrandSlider, FeaturedProductsList, ProductCard, CatalogueCard, AboutF, Strengths, Reach, BrandSliderF, BrandsF, TestimonialsF, EventsF, ProstigeF, SitemapF, CareersF, NewsUpdatesF
}